[package]
name = "rdoc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
colored = "2.0.0"
ferris-says = "0.2.1"
chrono = "0.4"
git2 = "0.14"
serde_derive = "1.0.137"
serde = "1.0.137"
serde_json = "1.0.81"
new_string_template = "1.3.1"